---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: poly-optimization-app
  namespace: poly
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poly-optimization-app
  template:
    metadata:
      labels:
        app: poly-optimization-app
    spec:
      containers:
        - name: poly-optimization-app
          image: koeng101/poly_optimization_app:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: poly-optimization-app-service
  namespace: poly
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: tcp
  selector:
    app: poly-optimization-app
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: poly-optimization-app-ingress
  namespace: poly
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: poly-optimization-app-tls
      hosts:
        - codonoptimizer.com
  rules:
  - host: codonoptimizer.com
    http:
      paths:
      - backend:
          serviceName: poly-optimization-app-service
          servicePort: 80
        path: /

